### ISSUE TITLE
Charging behaviour failed but returns 'success'  

### ISSUE THREAD

**Issue by kunzel** [strands-project/scitos_apps#39]
We observed that the charging behaviour failed, i.e. the robot was not on the docking station, but the response from the action server was nevertheless a 'success'. This happened on the real robot (spotted by @BFALacerda) and in  simulation (spotted by @kunzel). 

As result the robot sits just there and waits until it is fully charged which will never happen.

**Comment by gestom** [comment]
Does it happen randomly or is the error repeatable ?

**Comment by gestom** [comment]
@kunzel  Would you be able to set up simulator scene in a way that this error happens always ?

**Comment by bfalacerda** [comment]
I think the real life error happened because it was 5.45, thus the robot was in the dark (I'm going to open a question about this). It basically tried and failed twice, outputting "aborted". The state machine basically retries the docking when that happens, and on the third time the action outputted "succeeded", even though it didn't succeed. The state machine then went to the CHARGING state
