### ISSUE TITLE
Controller perpetually sending data,

### ISSUE THREAD

**Issue by markrosoft** [strands-project/scitos_apps#4]
The current joystick script is constantly sending data to the eye, in an attempt to emulate the closed eyed nature of sleeping whilst charging I found the thing demoniacally blinked

**Comment by cdondrup** [comment]
That's absolutely right. The driver for the joystick continuously publishes the current state of the joystick and thereby triggers the callback of the teleop node a few times a second. It would be good to just save the last message the teleop received and only send data when the next message is different (which should be fairly easy) and ideally it should just publish on those topics that are associated with the changes in the message.
The only problem at the moment is that the teleop control is split into three different nodes (movement incl. action buttons, head movement and eye movement). So to do it right imho the head and eye movement should be integrated in the c++ binary of the base movement before applying the mentioned changes.
If you feel ambitious @markrosoft you can just fork the repo, make the changes and open a pull request, otherwise I might do it next week.

**Comment by cburbridge** [comment]
I think that at lincoln last week, @hawesie was of the opinion that the head teleop was better in multiple separate nodes?

**Comment by cdondrup** [comment]
That's true the easiest thing to do would just start the base teleop control without the head and eyes. But always starting several nodes separately is not that convenient to me. But I might be convinced of its benefits.

**Comment by marc-hanheide** [comment]
I'd agree with Nick that having it as separate nodes makes sense as long as there are convenient launch files to start it all at once. Basically. I think the joystick base control should be a de-facto default to run on the robot, because it offer the emergency stop service. The other nodes (head and eye) are more specific, I'd say. But I'd agree to merge head and eye control into one.

**Comment by cdondrup** [comment]
Sounds reasonable to me.

**Comment by hawesie** [comment]
And to me. I can easily imagine us replacing head/eye control with an autonomous system, but the joystick is essential.

**Comment by cdondrup** [comment]
Closed a long time ago via pull request mentioned above.
