### ISSUE TITLE
preparation for first release

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_apps#94]
This repository needs a little restructuring according to the plans outlined in https://github.com/strands-project/strands_management/wiki/software-distribution

Most importantly, this repository should only contain scitos-specific apps, su as msgs, mux, dashboard, docking, teleop. Others to be moved to new `strands_apps`

Once this is complete, the repository's dependencies should be checked, the `README.md` and `package.xml` updated, and it should be released as outlined in https://github.com/strands-project/strands_management/wiki/STRANDS-release-procedures

**Comment by cdondrup** [comment]
Just my two cents about the packages inside this repository:
- `scitos_apps_msgs`: should be moved to the respective packages (teleop, charging, and rampclimb). This would require refactoring of the dependencies of other packages as well.
- `scitos_cmd_vel_mux`: just a collection of launch and config files. Can stay.
- `scitos_dashboard`: rather robot specific due to the service and topic names used in the code. Can stay but requires our version of the `scitos_node` running and publishing the right services and topics. Hence it should include `scitos_mira` as a run dependecy. @cburbridge 
- `scitos_door_pass`: No idea how robot specific this is. Would that work on any robot with a laser? I guess the laser would have to be in the same position?! @gestom 
- `scitos_ramp_climb`: see `scitos_door_pass`
- `scitos_docking`: uses some of the features of the robot. Can stay.
- `scitos_ptu`: Does this contain code specific to the robot or to the PTU and if it only contains PTU specific code, should it stay? @cburbridge @RaresAmbrus  The mirror head thing was just me playing around in the early stages and can go
- `scitos_reconfigure_inflation`: Does not seem to contain anything robot specific (except for the magic number of the inflation radius?!) and should therefore go to `strands_apps`. @RaresAmbrus 
- `scitos_teleop` and `scitos_touch`: Are both robot specific and can stay.
- `state_checker`: Does not contain any robot specific code and should therefore got to `strands_apps` @RaresAmbrus 

If the people I tagged or anyone else disagrees please speak now or forever hold your peace.

**Comment by marc-hanheide** [comment]
this all makes perfect sense to me! Thanks @cdondrup for taking action.

**Comment by cdondrup** [comment]
done
